beheadPermission: playerheads.canbehead
badwords:
  - nigger
  - nigga
  - nibba
  - nigqa
  - niqqa
  - niglet
  - chink
  - kike
  - anal,analysis,canals
  - anus
  - arse
  - ass,bassy,bass,crass,sass
  - ballsack
  - bastard
  - bitch
  - biatch
  - blowjob
  - blow job
  - boner
  - boob
  - buttplug
  - clitoris
  - cock
  - coon,raccoon
  - cunt
  - cum,scum
  - cumming
  - cums
  - damn
  - dick
  - dildo
  - dyke
  - fag
  - fagget
  - faggot
  - feck
  - fellate
  - fellatio
  - felching
  - fuck
  - fucc
  - fuk
  - phuck
  - fudgepacker
  - fudge packer
  - flange
  - Goddamn
  - God damn
  - hell,shell
  - jizz
  - knob end
  - labia
  - penis
  - piss
  - pube
  - pussy
  - queer
  - scrotum
  - sex
  - shit
  - slut
  - sperm
  - tit,stitch
  - tosser
  - twat
  - vagina
  - wank
  - whore
  - wtf